// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: core.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Method       string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path         string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	PathSegments []string               `protobuf:"bytes,4,rep,name=path_segments,json=pathSegments,proto3" json:"path_segments,omitempty"`
	Query        []*KeyValue            `protobuf:"bytes,5,rep,name=query,proto3" json:"query,omitempty"`
	// Body is `Value` rather than `Struct` so policies can inspect array
	// and scalar bodies as well as JSON objects. Field-access expressions
	// (`request.body.foo`) still work — CEL exposes `Value` as `dyn`.
	Body          *structpb.Value `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetPathSegments() []string {
	if x != nil {
		return x.PathSegments
	}
	return nil
}

func (x *Request) GetQuery() []*KeyValue {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Request) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Body is `Value` rather than `Struct` so the upstream client can
	// accept array and scalar JSON responses too (paginated cursors,
	// attachment listings). Object-shaped responses still expose
	// field access via `dyn` semantics.
	Body          *structpb.Value `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Output of the in-CEL helper functions (`get(path)`, `post(path, body)`, ...)
// used inside meta `request` expressions to describe an upstream call.
// Distinct from `Request`, which models the incoming proxied request.
type MetaRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Body   *structpb.Value        `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Content-Type to send the body with on the wire. Empty means
	// application/json (the historical default). post_form sets it to
	// application/x-www-form-urlencoded so Slack-style endpoints (which
	// reject xoxc browser-session tokens carrying JSON bodies) get the
	// shape they expect.
	ContentType   string `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *MetaRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MetaRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MetaRequest) GetBody() *structpb.Value {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MetaRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Principal identifies the caller for policy evaluation. The runtime does
// not interpret these fields itself; policies read them via the top-level
// `principal` CEL variable. Kept deliberately small so growing it (new
// scopes, attributes) does not couple the runtime to JWT specifics.
type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id for the caller. JWT `sub` claim in the proxy data plane.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Coarse classifier: "user" | "agent" | "service". The runtime does
	// not interpret this; policies may.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Granted scopes. Examples: "admin", "gmail:read".
	Scopes []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Open-ended attributes (email, team, ...) so deployments can attach
	// values without re-versioning the proto. map<string,string> keeps CEL
	// access ergonomic (`principal.attributes.team == "finance"`).
	Attributes    map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{4}
}

func (x *Principal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Principal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Principal) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *Principal) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\abouncer\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\x01\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12#\n" +
	"\rpath_segments\x18\x04 \x03(\tR\fpathSegments\x12'\n" +
	"\x05query\x18\x05 \x03(\v2\x11.bouncer.KeyValueR\x05query\x12*\n" +
	"\x04body\x18\x06 \x01(\v2\x16.google.protobuf.ValueR\x04bodyJ\x04\b\x02\x10\x03\"6\n" +
	"\bResponse\x12*\n" +
	"\x04body\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04body\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x88\x01\n" +
	"\vMetaRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12*\n" +
	"\x04body\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04body\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"\xd4\x01\n" +
	"\tPrincipal\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12B\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\".bouncer.Principal.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*github.com/jkylling/bouncer/internal/pb;pbb\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_proto_goTypes = []any{
	(*Request)(nil),        // 0: bouncer.Request
	(*Response)(nil),       // 1: bouncer.Response
	(*KeyValue)(nil),       // 2: bouncer.KeyValue
	(*MetaRequest)(nil),    // 3: bouncer.MetaRequest
	(*Principal)(nil),      // 4: bouncer.Principal
	nil,                    // 5: bouncer.Principal.AttributesEntry
	(*structpb.Value)(nil), // 6: google.protobuf.Value
}
var file_core_proto_depIdxs = []int32{
	2, // 0: bouncer.Request.query:type_name -> bouncer.KeyValue
	6, // 1: bouncer.Request.body:type_name -> google.protobuf.Value
	6, // 2: bouncer.Response.body:type_name -> google.protobuf.Value
	6, // 3: bouncer.MetaRequest.body:type_name -> google.protobuf.Value
	5, // 4: bouncer.Principal.attributes:type_name -> bouncer.Principal.AttributesEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
