package admin

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io/fs"
	"log/slog"
	"net/http"
	"os"
	"text/template"

	"github.com/go-chi/chi/v5"
)

// Install endpoints serve the bootstrap artifacts the /bouncer:setup
// MCP prompt instructs an agent to fetch. Both endpoints are gated by
// the internal-policy middleware against the `install_wrapper` /
// `install_ca_pem` actions (declared in internal_apis/api.yaml).
//
// The wrapper script is tenant-specific in the sense that the proxy
// URL baked into it is derived from the request the caller used
// (Host + scheme, honoring X-Forwarded-Host / -Proto). Self-hosted
// local users hitting http://localhost:8080 get that URL; a hosted
// deployment behind a reverse proxy gets its public URL.
const (
	InstallWrapperPath = "/install/bouncer-wrap"
	InstallCAPath      = "/install/ca.pem"
)

// MountInstall attaches the install endpoints. caPath may be empty
// (MITM disabled); the ca.pem handler 404s in that case, mirroring
// MountCA's behavior.
func MountInstall(r chi.Router, caPath string) {
	r.Get(InstallWrapperPath, installWrapperHandler())
	r.Get(InstallCAPath, installCAHandler(caPath))
}

// wrapperScriptTemplate is the POSIX shell wrapper rendered per
// request. The single substitution slot is .ProxyURL; everything else
// is verbatim. See plans/bouncer_setup_mcp_tool.md for the design
// rationale (HTTPS_PROXY / SSL_CERT_FILE / etc.).
const wrapperScriptTemplate = `#!/bin/sh
# bouncer-wrap — run a command through the bouncer proxy.
#
# Generated by bouncer. Re-fetch from the install endpoint to refresh.

set -eu

BOUNCER_PROXY="{{ .ProxyURL }}"

: "${BOUNCER_HOME:=$HOME/.config/bouncer}"
CERT="$BOUNCER_HOME/ca.pem"

if [ ! -f "$CERT" ]; then
  echo "bouncer-wrap: $CERT not found. Re-run /bouncer:setup." >&2
  exit 1
fi

if [ "$#" -eq 0 ]; then
  echo "usage: bouncer-wrap <command> [args...]" >&2
  exit 64
fi

exec env \
  HTTPS_PROXY="$BOUNCER_PROXY" \
  https_proxy="$BOUNCER_PROXY" \
  HTTP_PROXY="$BOUNCER_PROXY" \
  http_proxy="$BOUNCER_PROXY" \
  SSL_CERT_FILE="$CERT" \
  REQUESTS_CA_BUNDLE="$CERT" \
  NODE_EXTRA_CA_CERTS="$CERT" \
  "$@"
`

// installWrapperHandler renders the wrapper script with .ProxyURL set
// from the incoming request. Compile the template once at handler
// construction.
func installWrapperHandler() http.HandlerFunc {
	tmpl := template.Must(template.New("bouncer-wrap").Parse(wrapperScriptTemplate))
	return func(w http.ResponseWriter, r *http.Request) {
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, struct{ ProxyURL string }{ProxyURL: externalURL(r)}); err != nil {
			slog.ErrorContext(r.Context(), "install: render wrapper", "err", err)
			writeJSONError(w, "server error", http.StatusInternalServerError)
			return
		}
		body := buf.Bytes()
		writeInstallBytes(w, body, "text/x-shellscript; charset=utf-8", "bouncer-wrap")
	}
}

// installCAHandler serves the same bytes as MountCA's handler but
// auth-gated and under a different filename. Reading per-request
// keeps the handler honest when an operator regenerates the CA
// without a process restart (same reasoning as ca.go).
func installCAHandler(caPath string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if caPath == "" {
			writeJSONError(w, "MITM disabled — no CA configured", http.StatusNotFound)
			return
		}
		body, err := os.ReadFile(caPath)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				writeJSONError(w, "CA cert not found", http.StatusNotFound)
				return
			}
			slog.ErrorContext(r.Context(), "install: read ca", "path", caPath, "err", err)
			writeJSONError(w, "server error", http.StatusInternalServerError)
			return
		}
		writeInstallBytes(w, body, "application/x-pem-file", "ca.pem")
	}
}

// writeInstallBytes is the common write path for install artifacts.
// Both endpoints share a no-store cache policy, attachment-mode
// content disposition with the canonical client-side filename, and
// an X-Bouncer-Sha256 header the /bouncer:setup prompt cites as the
// `expected: …` value the user verifies against.
func writeInstallBytes(w http.ResponseWriter, body []byte, contentType, filename string) {
	sum := sha256.Sum256(body)
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
	w.Header().Set("X-Bouncer-Sha256", hex.EncodeToString(sum[:]))
	_, _ = w.Write(body)
}

// externalURL determines the public-facing URL to bake into the
// wrapper script. The order:
//
//  1. X-Forwarded-Proto + X-Forwarded-Host (reverse-proxy terminating
//     TLS in front of bouncer)
//  2. r.TLS state + r.Host (direct connection)
//
// Both forwarded headers are honored independently — a deployment
// that terminates TLS upstream typically sets only X-Forwarded-Proto
// while keeping Host as the public hostname.
func externalURL(r *http.Request) string {
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	if v := r.Header.Get("X-Forwarded-Proto"); v != "" {
		scheme = v
	}
	host := r.Host
	if v := r.Header.Get("X-Forwarded-Host"); v != "" {
		host = v
	}
	return scheme + "://" + host
}
